apiVersion: 1

notifiers:
  - name: Water SLO Email Notification
    type: email
    uid: water-slo-email
    isDefault: false
    settings:
      addresses: 'avinashvp@gmail.com'
      singleEmail: false
    secureSettings:
      password: ''

