apiVersion: 1
datasources:
  - name: IoT Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"
      tlsSkipVerify: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""