receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'iot-app'
          scrape_interval: 15s
          metrics_path: /metrics
          static_configs:
            - targets: ['iot-app:8000']

processors:
  batch:
    timeout: 5s
    send_batch_size: 100

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
